name: collect data

on: 
  schedule:
    - cron: '1 0 11 * *' # Runs on 00:01 at every 11th day of each month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.6' # Install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: collect news
        run: python3 news.py

      - name: collect prices
        run: python3 collectPrices.py

      - name: commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m 'Collected News and Prices' --alow-empty)

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main